window.env = {
  "SHELL": "/usr/sbin/zsh",
  "npm_command": "start",
  "SESSION_MANAGER": "local/tufgaming:@/tmp/.ICE-unix/3236,unix/tufgaming:/tmp/.ICE-unix/3236",
  "USER_ZDOTDIR": "/home/britto/Source/School Work/Sem 5/COMP 3123",
  "npm_config_userconfig": "/home/britto/Source/School Work/Sem 5/COMP 3123/.npmrc",
  "COLORTERM": "truecolor",
  "XDG_CONFIG_DIRS": "/etc/xdg",
  "npm_config_cache": "/home/britto/Source/School Work/Sem 5/COMP 3123/.npm",
  "XDG_MENU_PREFIX": "gnome-",
  "TERM_PROGRAM_VERSION": "1.94.2",
  "GTK_IM_MODULE": "ibus",
  "VCPKG_DISABLE_METRICS": "1",
  "HOSTNAME": "tufgaming",
  "NODE": "/usr/bin/node",
  "LC_ADDRESS": "en_CA.UTF-8",
  "LC_NAME": "en_CA.UTF-8",
  "SSH_AUTH_SOCK": "/run/user/1000/gcr/ssh",
  "DOTNET_CLI_TELEMETRY_OPTOUT": "1",
  "XDG_DATA_HOME": "/home/britto/Source/School Work/Sem 5/COMP 3123/.local/share",
  "GRADLE_HOME": "/usr/share/java/gradle",
  "P9K_TTY": "old",
  "XDG_CONFIG_HOME": "/home/britto/Source/School Work/Sem 5/COMP 3123/.config",
  "MEMORY_PRESSURE_WRITE": "c29tZSAyMDAwMDAgMjAwMDAwMAA=",
  "COLOR": "1",
  "npm_config_local_prefix": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend",
  "XMODIFIERS": "@im=ibus",
  "GNUPGHOME": "/home/britto/.local/share/gnupg",
  "DESKTOP_SESSION": "gnome",
  "DISTROBOX_ENTER_PATH": "/usr/bin/distrobox-enter",
  "LC_MONETARY": "en_CA.UTF-8",
  "NO_AT_BRIDGE": "1",
  "npm_config_globalconfig": "/etc/npmrc",
  "EDITOR": "nano",
  "GOBIN": "/home/britto/.local/dev/go/bin",
  "PWD": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend",
  "VCPKG_ROOT": "/home/britto/.local/vcpkg",
  "LOGNAME": "britto",
  "XDG_SESSION_DESKTOP": "gnome",
  "XDG_SESSION_TYPE": "wayland",
  "npm_config_init_module": "/home/britto/Source/School Work/Sem 5/COMP 3123/.npm-init.js",
  "SYSTEMD_EXEC_PID": "186581",
  "_": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend/node_modules/.bin/react-dotenv",
  "XAUTHORITY": "/run/user/1000/.mutter-Xwaylandauth.YZ9OX2",
  "VSCODE_GIT_ASKPASS_NODE": "/opt/vscodium-bin/codium",
  "container": "podman",
  "MOTD_SHOWN": "pam",
  "VSCODE_INJECTION": "1",
  "GDM_LANG": "en_CA.UTF-8",
  "HOME": "/home/britto/Source/School Work/Sem 5/COMP 3123",
  "USERNAME": "britto",
  "LANG": "en_CA.UTF-8",
  "LC_PAPER": "en_CA.UTF-8",
  "XDG_CURRENT_DESKTOP": "GNOME",
  "npm_package_version": "0.1.0",
  "MEMORY_PRESSURE_WATCH": "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/app-dbus\\x2d:1.2\\x2dorg.gnome.Console.slice/dbus-:1.2-org.gnome.Console@0.service/memory.pressure",
  "VTE_VERSION": "7801",
  "WAYLAND_DISPLAY": "wayland-0",
  "GIT_ASKPASS": "/opt/vscodium-bin/resources/app/extensions/git/dist/askpass.sh",
  "INVOCATION_ID": "7c2ae9208695438a908946417f1f4dcd",
  "MANAGERPID": "3114",
  "INIT_CWD": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend",
  "CHROME_DESKTOP": "codium-url-handler.desktop",
  "CONTAINER_ID": "COMP3123",
  "XDG_CACHE_HOME": "/home/britto/Source/School Work/Sem 5/COMP 3123/.cache",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "GNOME_SETUP_DISPLAY": ":1",
  "npm_config_npm_version": "10.9.0",
  "XDG_SESSION_CLASS": "user",
  "TERM": "xterm-256color",
  "LC_IDENTIFICATION": "en_CA.UTF-8",
  "npm_package_name": "frontend",
  "npm_config_prefix": "/usr",
  "ZDOTDIR": "/home/britto/Source/School Work/Sem 5/COMP 3123",
  "USER": "britto",
  "VSCODE_GIT_IPC_HANDLE": "/run/user/1000/vscode-git-079012ab52.sock",
  "DISTROBOX_HOST_HOME": "/home/britto",
  "DISPLAY": ":0",
  "npm_lifecycle_event": "start",
  "SHLVL": "7",
  "MOZ_ENABLE_WAYLAND": "1",
  "TESTCONTAINERS_RYUK_DISABLED": "true",
  "LC_TELEPHONE": "en_CA.UTF-8",
  "QT_IM_MODULE": "ibus",
  "LC_MEASUREMENT": "en_CA.UTF-8",
  "npm_config_user_agent": "npm/10.9.0 node/v23.1.0 linux x64 workspaces/false",
  "TERMINFO_DIRS": "/usr/share/terminfo:/run/host/usr/share/terminfo",
  "XDG_STATE_HOME": "/home/britto/Source/School Work/Sem 5/COMP 3123/.local/state",
  "npm_execpath": "/usr/lib/node_modules/npm/bin/npm-cli.js",
  "XDG_RUNTIME_DIR": "/run/user/1000",
  "DEBUGINFOD_URLS": "https://debuginfod.archlinux.org ",
  "npm_package_json": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend/package.json",
  "LC_TIME": "en_CA.UTF-8",
  "DOCKER_HOST": "unix:///run/user/1000/podman/podman.sock",
  "P9K_SSH": "0",
  "VSCODE_GIT_ASKPASS_MAIN": "/opt/vscodium-bin/resources/app/extensions/git/dist/askpass-main.js",
  "JOURNAL_STREAM": "8:429496",
  "XDG_DATA_DIRS": "/home/britto/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/usr/local/share:/usr/share",
  "GDK_BACKEND": "x11",
  "npm_config_noproxy": "",
  "BROWSER": "firefox",
  "PATH": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend/node_modules/.bin:/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/node_modules/.bin:/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/node_modules/.bin:/home/britto/Source/School Work/Sem 5/COMP 3123/node_modules/.bin:/home/britto/Source/School Work/Sem 5/node_modules/.bin:/home/britto/Source/School Work/node_modules/.bin:/home/britto/Source/node_modules/.bin:/home/britto/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/home/britto/.dotnet/tools:/home/britto/.local/dev/go/bin:/home/britto/.local/share/gem/ruby/3.0.0/bin:/home/britto/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/home/britto/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sbin:/sbin:/bin",
  "npm_config_node_gyp": "/usr/lib/node_modules/node-gyp/bin/node-gyp.js",
  "GDMSESSION": "gnome",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "GNOME",
  "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
  "npm_config_global_prefix": "/usr",
  "MAIL": "/var/spool/mail/britto",
  "npm_node_execpath": "/usr/bin/node",
  "LC_NUMERIC": "en_CA.UTF-8",
  "OLDPWD": "/home/britto/Source/School Work/Sem 5/COMP 3123/Assignments/101416601_comp3123_assignment/frontend",
  "GOPATH": "/home/britto/.local/dev/go",
  "TERM_PROGRAM": "vscode"
};